#!/usr/bin/env python3
"""Local dev server: serves public/ and mocks the two API endpoints.

The record it returns is NOT hand-written — it is generated by the real Worker
engine (api/src/index.js -> buildRecord) so the front-end is always rendering the
true schema. Regenerate with test/mkrecord.mjs.

    python3 test/mock-api.py            # -> http://127.0.0.1:8791
"""
import http.server, json, os, socketserver, sys, time

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public')
HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURE = os.path.join(HERE, 'record.manageable.json')
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8791
DELAY = float(os.environ.get('MOCK_DELAY', '2.0'))   # stand in for the vision call


class H(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=ROOT, **kw)

    def _json(self, obj, status=200):
        b = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header('content-type', 'application/json')
        self.send_header('content-length', str(len(b)))
        self.end_headers()
        self.wfile.write(b)

    def do_GET(self):
        # Dev-only fixture route, so a browser can drive the upload path without
        # a file picker. Fixtures live in test/, never in the deploy root.
        if self.path.startswith('/__fixtures/'):
            name = os.path.basename(self.path)
            path = os.path.join(HERE, 'fixtures', name)
            if os.path.isfile(path):
                with open(path, 'rb') as f:
                    b = f.read()
                self.send_response(200)
                self.send_header('content-type', 'image/jpeg')
                self.send_header('content-length', str(len(b)))
                self.end_headers()
                self.wfile.write(b)
                return
            self._json({'error': 'no_fixture'}, 404)
            return

        # The saved-reading endpoint the /report page reads. Same route the
        # Worker serves from KV; ?tier= picks which generated record comes back
        # so every report shape can be opened by link locally.
        if self.path.startswith('/api/report/'):
            path, _, query = self.path.partition('?')
            # The page only ever sends an id, so the id IS the switch here:
            #   /report?id=medical  opens the medical fixture.
            # Anything else falls back to manageable.
            scan_id = path.rsplit('/', 1)[-1]
            tier = scan_id if scan_id in ('healthy', 'manageable', 'medical', 'unclear') else 'manageable'
            for pair in query.split('&'):
                if pair.startswith('tier='):
                    tier = pair[5:]
            fixture = os.path.join(HERE, f'record.{tier}.json')
            if not os.path.isfile(fixture):
                fixture = FIXTURE
            with open(fixture) as f:
                rec = json.load(f)
            rec = rec.get('record', rec)
            rec.pop('lead', None)
            return self._json(rec)

        # Cloudflare Pages serves /report.html for /report (see public/_redirects).
        # Mirror it here, so a local walk-through follows the exact URLs the CRM
        # and the follow-up email will contain.
        clean, _, _q = self.path.partition('?')
        if clean == '/report':
            self.path = '/report.html'

        super().do_GET()

    def do_POST(self):
        n = int(self.headers.get('content-length') or 0)
        body = json.loads(self.rfile.read(n) or b'{}')
        path, _, query = self.path.partition('?')
        if path == '/api/analyze-nails':
            # ?tier=healthy|manageable|medical|unclear picks which generated
            # record to return, so every report shape can be walked locally.
            tier = 'manageable'
            for pair in query.split('&'):
                if pair.startswith('tier='):
                    tier = pair[5:]
            fixture = os.path.join(HERE, f'record.{tier}.json')
            if not os.path.isfile(fixture):
                fixture = FIXTURE
            print(f'  [mock] analyze tier={tier}: image {len(body.get("image",""))} b64 chars')
            time.sleep(DELAY)
            with open(fixture) as f:
                return self._json(json.load(f))
        if path == '/api/plan':
            # What GHL would receive when somebody saves reminders to her phone.
            print('  [mock] plan saved:',
                  {k: v for k, v in body.items() if k != 'items'},
                  '| items:', [i.get('title') for i in body.get('items', [])])
            return self._json({'ok': True, 'matched': True})
        if path == '/api/lead':
            print('  [mock] lead:', {k: v for k, v in body.items() if k != 'image'})
            return self._json({'ok': True, 'delivered': True})
        self._json({'error': 'not_found'}, 404)

    def log_message(self, fmt, *args):
        pass


socketserver.TCPServer.allow_reuse_address = True
with socketserver.TCPServer(('127.0.0.1', PORT), H) as s:
    print(f'mock serving {ROOT} on http://127.0.0.1:{PORT}  (vision delay {DELAY}s)')
    s.serve_forever()
