#!/usr/bin/env python3
"""Local dev server: serves public/ and mocks the two API endpoints.

The record it returns is NOT hand-written — it is generated by the real Worker
engine (api/src/index.js -> buildRecord) so the front-end is always rendering the
true schema. Regenerate with test/mkrecord.mjs.

    python3 test/mock-api.py            # -> http://127.0.0.1:8791
"""
import http.server, json, os, socketserver, sys, time

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'public')
FIXTURE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'record.manageable.json')
PORT = int(sys.argv[1]) if len(sys.argv) > 1 else 8791
DELAY = float(os.environ.get('MOCK_DELAY', '2.0'))   # stand in for the vision call


class H(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=ROOT, **kw)

    def _json(self, obj, status=200):
        b = json.dumps(obj).encode()
        self.send_response(status)
        self.send_header('content-type', 'application/json')
        self.send_header('content-length', str(len(b)))
        self.end_headers()
        self.wfile.write(b)

    def do_GET(self):
        # Dev-only fixture route, so a browser can drive the upload path without
        # a file picker. Fixtures live in test/, never in the deploy root.
        if self.path.startswith('/__fixtures/'):
            name = os.path.basename(self.path)
            path = os.path.join(os.path.dirname(FIXTURE), 'fixtures', name)
            if os.path.isfile(path):
                with open(path, 'rb') as f:
                    b = f.read()
                self.send_response(200)
                self.send_header('content-type', 'image/jpeg')
                self.send_header('content-length', str(len(b)))
                self.end_headers()
                self.wfile.write(b)
                return
            self._json({'error': 'no_fixture'}, 404)
            return
        super().do_GET()

    def do_POST(self):
        n = int(self.headers.get('content-length') or 0)
        body = json.loads(self.rfile.read(n) or b'{}')
        if self.path == '/api/analyze-nails':
            print(f'  [mock] analyze: image {len(body.get("image",""))} b64 chars')
            time.sleep(DELAY)
            with open(FIXTURE) as f:
                return self._json(json.load(f))
        if self.path == '/api/lead':
            print('  [mock] lead:', {k: v for k, v in body.items() if k != 'image'})
            return self._json({'ok': True, 'delivered': True})
        self._json({'error': 'not_found'}, 404)

    def log_message(self, fmt, *args):
        pass


socketserver.TCPServer.allow_reuse_address = True
with socketserver.TCPServer(('127.0.0.1', PORT), H) as s:
    print(f'mock serving {ROOT} on http://127.0.0.1:{PORT}  (vision delay {DELAY}s)')
    s.serve_forever()
